version: '3.8'

services:
  postgres:
    container_name: fastfeet-api-nest
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fastfeet-nest
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres